version: '3.4'

services:
  nginx:
    build: nginx
    restart: always
    ports:
      - "7788:80"
  mysql:
    image: mariadb
    restart: always
    depends_on:
      - nginx
    volumes:
      - './database:/var/lib/mysql'
  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - nginx
      - mysql
    environment:
      PMA_HOST: mysql
  frontend:
    build: frontend
    restart: always
    depends_on:
      - nginx
  pdf-analyzer:
    build: pdf-analyzer
    restart: always
    depends_on:
      - nginx
    volumes:
      - ./uploads:/app/uploads
    environment:
      PORT: 7000
  backend:
    build: backend
    restart: always
    depends_on:
      - nginx
      - mysql
      - pdf-analyzer
    volumes:
      - ./uploads:/app/uploads
    environment:
      PORT: 9000
      LOG_LEVEL: "debug"
